backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages du site"
    files:
      - file: "index.html"
        label: "Page d'accueil complète"
        name: "home"
        fields:
          - {label: "Contenu HTML complet (Textes & Photos)", name: "body", widget: "markdown"}
